SELECT 
   
    DIM_EMPLEADO.Id AS "ID_EMPLEADO",
	DIM_PRODUCTO.Id AS "ID_PRODUCTO",
	DIM_CLIENTE.Id AS "ID_CLIENTE",
	DIM_TIEMPO.Tiempo_id AS "ID_TIEMPO",
    DIM_ALMACEN.Id AS "ID_ALMACEN",
	DETALLEVENTAS_REL.Cantidad AS "CANTIDAD",
	SUM(DETALLEVENTAS_REL.PrecioUnitario) AS "TOTAL",
	(DETALLEVENTAS_REL.PrecioUnitario* DETALLEVENTAS_REL.Cantidad) AS "INGRESOS"




FROM BikeZ.dbo.Almacenes AS ALMACEN_REL
INNER JOIN BikeZ.dbo.Territorios AS TERRITORIO_REL ON (ALMACEN_REL.TerritorioID = TERRITORIO_REL.TerritorioID)
INNER JOIN BikeZ.dbo.Empleados AS EMPLEADOS_REL    ON (TERRITORIO_REL.TerritorioID = EMPLEADOS_REL.TerritorioID)
INNER JOIN BikeZ.dbo.Ventas AS VENTAS_REL          ON (EMPLEADOS_REL.EmpleadoID = VENTAS_REL.VendedorID)
INNER JOIN BikeZ.dbo.Paises AS PAIS_REL            ON (TERRITORIO_REL.PaisID = PAIS_REL.PaisID)
INNER JOIN BikeZ.dbo.Clientes AS CLIENTES_REL      ON (CLIENTES_REL.ClienteID = VENTAS_REL.ClienteID)
INNER JOIN BikeZ.dbo.DetalleVentas AS DETALLEVENTAS_REL  ON (VENTAS_REL.VentaID = DETALLEVENTAS_REL.DetalleVentaID)
INNER JOIN BikeZ.dbo.Productos AS PRODUCTOS_REL    ON (DETALLEVENTAS_REL.ProductoID = PRODUCTOS_REL.ProductoID)
INNER JOIN BikeZ.dbo.Categorias AS CATEGORIA_REL   ON (PRODUCTOS_REL.CategoriaID = CATEGORIA_REL.CategoriaID)

--DIM

INNER JOIN Bike_Z.dbo.DIM_ALMACEN AS DIM_ALMACEN ON (DIM_ALMACEN.Almacen_id = ALMACEN_REL.AlmacenID)
INNER JOIN Bike_Z.dbo.DIM_PRODUCTO AS DIM_PRODUCTO  ON (DIM_PRODUCTO.Producto_id = PRODUCTOS_REL.ProductoID)
INNER JOIN Bike_Z.dbo.DIM_CLIENTE AS DIM_CLIENTE    ON (DIM_CLIENTE.Cliente_id = CLIENTES_REL.ClienteID)
INNER JOIN  Bike_Z.dbo.DIM_TIEMPO AS DIM_TIEMPO      ON (DIM_TIEMPO.Fecha_completa = VENTAS_REL.Fecha)
INNER JOIN Bike_Z.dbo.DIM_EMPLEADO AS DIM_EMPLEADO  ON (DIM_EMPLEADO.Empleado_id = EMPLEADOS_REL.EmpleadoID)

GROUP BY DIM_ALMACEN.Id, DIM_CLIENTE.Id, DIM_EMPLEADO.Id, DIM_PRODUCTO.Id,
DIM_TIEMPO.Tiempo_id, DETALLEVENTAS_REL.Cantidad, VENTAS_REL.Fecha, VENTAS_REL.FechaEnvio, 
DETALLEVENTAS_REL.Cantidad, DETALLEVENTAS_REL.PrecioUnitario